services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    environment:
      NODE_ENV: development

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    command: npm test
